### PR TITLE
amogus pog imposter

### PR DESCRIPTION
**Pull request by JackyBorderCollie**
**Resolves**

yes it adds a drip that tells you to play amogus

**Changes**

changed the file 404 to tell that to play amogus

**Reason for changes**

bEcAuSe EvErYoNe WoUlD pLaY aMoNg uS iF tHeY gEt ThE sUs 404 pAgE

**Tests**

nope i did not test

### CODE REVIEW

**Comment by JackyBorderCollie** [comment]
pog

**Comment by CluckCluckChicken** [comment]
increase the random.next thing to say 5 then commit

**Comment by JackyBorderCollie** [comment]
ok

**Comment by JackyBorderCollie** [comment]
ok done i added some sussy cases now invite me please

**Pull request merged**
