### PR TITLE
actually bother to gulp css

### PR DESCRIPTION
**Pull request by FunctionalMetatable**

### CODE REVIEW

**Comment by ScolderCreations** [comment]
I don’t think this would work, Potatophant said removing these caused a ton of error messages.

**Comment by FunctionalMetatable** [comment]
> I don’t think this would work, Potatophant said removing these caused a ton of error messages.

works for me tho

**Comment by ScolderCreations** [comment]
> > I don’t think this would work, Potatophant said removing these caused a ton of error messages.
> 
> works for me tho

Ah, it does? Excellent. This would drop loading times a lot

**Comment by FunctionalMetatable** [comment]
> > > I don’t think this would work, Potatophant said removing these caused a ton of error messages.
> > 
> > 
> > works for me tho
> 
> Ah, it does? Excellent. This would drop loading times a lot

no it wont

**Comment by FunctionalMetatable** [comment]
@CluckCluckChicken

**Pull request merged**
