### PR TITLE
Create an actual blacklist

### PR DESCRIPTION
**Pull request by gosoccerboy5**
um, i dont know how to do c# but if you keep needing to blacklist people then maybe creating a blacklist would be better.
should the blacklist be in a higher scope?

### CODE REVIEW

**Comment by CluckCluckChicken** [comment]
that bit of code only exists as a joke (its client side anyway so not very hard to go around), but this reminded be to add backend banning as well. [i added it now](https://github.com/CluckCluckChicken/Magnifier/commit/7813adc72306588a7342464c1b8d1e78690c129a). thanks!

**Comment by gosoccerboy5** [comment]
ok

**Comment by gosoccerboy5** [comment]
> that bit of code only exists as a joke (its client side anyway so not very hard to go around), but this reminded be to add backend banning as well. [i added it now](https://github.com/CluckCluckChicken/Magnifier/commit/7813adc72306588a7342464c1b8d1e78690c129a). thanks!

Out of curiosity, how does that work?

**Comment by CluckCluckChicken** [comment]
isbanned property, i should probably add some code to make it actually do stuff

**Comment by return-misaPuding** [comment]
I didn´t know how to make lists in C# and how to check whether the list contains something neither in C# nor JS so I used || in the boolean instead

**Comment by CluckCluckChicken** [comment]
`List<string> bigChungus = new List<string>();` creates and instantiates a list of strings
`bigChungus.Contains("the imposter from among us")` looks to see if the `bigChungus` list contains `"the imposter from among us"`

**Pull request closed without merging**
